using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace H4KeymapEditor.Models
{
    public enum Keycode : int
    {
        ESC,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PrintScreen,
        ScrollLock,
        Pause,
        Tilde,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Zero,
        Minus,
        Equals,
        Backspace,
        Tab,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        LeftBracket,
        RightBracket,
        Unknown0,
        CapsLock,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        Semicolon,
        Hash,
        Enter,
        LeftShift,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        Comma,
        Period,
        ForwardSlash,
        RightShift,
        LeftControl,
        WindowsKey,
        LeftAlt,
        Space,
        RightAlt,
        Unknown1,
        Unknown2,
        RightControl,
        UpArrow,
        DownArrow,
        LeftArrow,
        RightArrow,
        Insert,
        Home,
        PageUp,
        Delete,
        End,
        PageDown,
        NumLock,
        NumPadForwardSlash,
        NumPadMultiply,
        NumPadZero,
        NumPadOne,
        NumPadTwo,
        NumPadThree,
        NumPadFour,
        NumPadFive,
        NumPadSix,
        NumPadSeven,
        NumPadEight,
        NumPadNine,
        NumPadMinus,
        NumPadPlus,
        NumPadEnter,
        // The nex two crash when used and the two after that have odd behavior
        Unknown3DONOTUSE, 
        Unknown4DONOTUSE,
        Unknown5,
        Unknown6,
        Invalid = 0xFFFF
    }

    public class KeyBinding
    {
        // Add the offset to this to get the correct offset to write to the file
        public static long FileOffsetBase = 0x5D0;

        public string Name { get; }
        public Keycode PrimaryKey {  get; set; }
        public Keycode SecondaryKey { get; set; }
        public int? MovOffset { get; set; }
        public long MemoryOffset { get; }
        public bool Unknown { get; }

        public KeyBinding (string name, Keycode primaryKey, Keycode secondaryKey, long offset, bool unknown)
        {
            Name = name;
            PrimaryKey = primaryKey;
            SecondaryKey = secondaryKey;
            MemoryOffset = offset;
            Unknown = unknown;
        }

        public void ReadKeyBindings(byte[] bytes)
        {
            foreach (KeyBinding keyBinding in KeyBindings)
            {

            }
        }

        public static ObservableCollection<KeyBinding> KeyBindings = new ObservableCollection<KeyBinding>();

        public static readonly List<KeyBinding> DefaultKeyBindings = new List<KeyBinding>
        {
            new KeyBinding("Jump", Keycode.Space, Keycode.Invalid, 0x000, false),
            new KeyBinding("Swap Weapons", Keycode.One, Keycode.Invalid, 0x008, false),
            new KeyBinding("Interact", Keycode.E, Keycode.Invalid, 0x010, false),
            new KeyBinding("Melee", Keycode.Q, Keycode.Invalid, 0x018, false),
            new KeyBinding("Equipment", Keycode.LeftShift, Keycode.Invalid, 0x020, false),
            new KeyBinding("Throw Grenade", Keycode.G, Keycode.Invalid, 0x028, false),
            new KeyBinding("Fire Primary", Keycode.Invalid, Keycode.Invalid, 0x030, false),
            new KeyBinding("Crouch", Keycode.LeftControl, Keycode.Invalid, 0x038, false),
            new KeyBinding("Zoom", Keycode.Invalid, Keycode.Invalid, 0x040, false),
            new KeyBinding("Cycle Grenades Left", Keycode.Invalid, Keycode.Invalid, 0x048, false),
            new KeyBinding("Cycle Grenades Right", Keycode.Two, Keycode.Invalid, 0x050, false),
            new KeyBinding("Unknown 0", Keycode.Invalid, Keycode.Invalid, 0x058, true),
            new KeyBinding("Unknown 1", Keycode.B, Keycode.Invalid, 0x060, true),
            new KeyBinding("Unknown 2", Keycode.LeftBracket, Keycode.Invalid, 0x068, true),
            new KeyBinding("Unknown 3", Keycode.RightBracket, Keycode.Invalid, 0x070, true),
            new KeyBinding("Unknown 4", Keycode.P, Keycode.Invalid, 0x078, true),
            new KeyBinding("Unknown 5", Keycode.LeftBracket, Keycode.Invalid, 0x080, true),
            new KeyBinding("Unknown 6", Keycode.RightBracket, Keycode.Invalid, 0x088, true),
            new KeyBinding("Unknown 7", Keycode.R, Keycode.Invalid, 0x090, true),
            new KeyBinding("Unknown 8", Keycode.ESC, Keycode.Invalid, 0x098, true),
            new KeyBinding("Unknown 9", Keycode.ESC, Keycode.Invalid, 0x0A0, true),
            new KeyBinding("Unknown 10", Keycode.ESC, Keycode.Invalid, 0x0A8, true),
            new KeyBinding("Unknown 11", Keycode.Invalid, Keycode.Invalid, 0x0B0, true),
            new KeyBinding("Unknown 12", Keycode.Invalid, Keycode.Invalid, 0x0B8, true),
            new KeyBinding("Unknown 13", Keycode.Invalid, Keycode.Invalid, 0x0C0, true),
            new KeyBinding("Unknown 14", Keycode.Four, Keycode.Invalid, 0x0C8, true),
            new KeyBinding("Unknown 15", Keycode.ESC, Keycode.Invalid, 0x0D0, true),
            new KeyBinding("Unknown 16", Keycode.DownArrow, Keycode.Invalid, 0x0D8, true),
            new KeyBinding("Unknown 17", Keycode.UpArrow, Keycode.Invalid, 0x0E0, true),
            new KeyBinding("Unknown 18", Keycode.LeftArrow, Keycode.Invalid, 0x0E8, true),
            new KeyBinding("Unknown 19", Keycode.RightArrow, Keycode.Invalid, 0x0F0, true),
            new KeyBinding("Unknown 20", Keycode.R, Keycode.Invalid, 0x0F8, true),
            new KeyBinding("Unknown 21", Keycode.G, Keycode.Invalid, 0x100, true),
            new KeyBinding("Unknown 22", Keycode.Invalid, Keycode.Invalid, 0x108, true),
            new KeyBinding("Unknown 23", Keycode.Space, Keycode.Invalid, 0x110, true),
            new KeyBinding("Unknown 24", Keycode.Invalid, Keycode.Invalid, 0x118, true),
            new KeyBinding("Unknown 25", Keycode.Invalid, Keycode.Invalid, 0x120, true),
            new KeyBinding("Scoreboard", Keycode.Tab, Keycode.Invalid, 0x128, false),
            new KeyBinding("Unknown 26", Keycode.Invalid, Keycode.Invalid, 0x130, true),
            new KeyBinding("Unknown 27", Keycode.Semicolon, Keycode.Invalid, 0x138, true),
            new KeyBinding("Sprint", Keycode.C, Keycode.Invalid, 0x140, false),
            new KeyBinding("Unknown 28", Keycode.Invalid, Keycode.Invalid, 0x148, true),
            new KeyBinding("Unknown 29", Keycode.X, Keycode.Invalid, 0x150, true),
            new KeyBinding("Unknown 30", Keycode.Invalid, Keycode.Invalid, 0x158, true),
            new KeyBinding("Unknown 31", Keycode.Invalid, Keycode.Invalid, 0x160, true),
            new KeyBinding("Unknown 32", Keycode.Q, Keycode.Invalid, 0x168, true),
            new KeyBinding("Unknown 33", Keycode.LeftControl, Keycode.Invalid, 0x170, true),
            new KeyBinding("Zoom In", Keycode.Z, Keycode.Invalid, 0x178, false),
            new KeyBinding("Zoom Out", Keycode.X, Keycode.Invalid, 0x180, false),
            new KeyBinding("Reload", Keycode.R, Keycode.Invalid, 0x188, false),
            new KeyBinding("Unknown 34", Keycode.Zero, Keycode.Invalid, 0x190, true),
            new KeyBinding("Unknown 35", Keycode.One, Keycode.Invalid, 0x198, true),
            new KeyBinding("Unknown 36", Keycode.Insert, Keycode.Invalid, 0x1A0, true),
            new KeyBinding("Unknown 37", Keycode.One, Keycode.Invalid, 0x1A8, true),
            new KeyBinding("Unknown 38", Keycode.Invalid, Keycode.Invalid, 0x1B0, true),
            new KeyBinding("Unknown 39", Keycode.Two, Keycode.Invalid, 0x1B8, true),
            new KeyBinding("Unknown 40", Keycode.X, Keycode.Invalid, 0x1C0, true),
            new KeyBinding("Unknown 41", Keycode.H, Keycode.Invalid, 0x1C8, true),
            new KeyBinding("Unknown 42", Keycode.C, Keycode.Invalid, 0x1D0, true),
            new KeyBinding("Unknown 43", Keycode.Invalid, Keycode.Invalid, 0x1D8, true),
            new KeyBinding("Unknown 44", Keycode.LeftControl, Keycode.Invalid, 0x1E0, true),
            new KeyBinding("Unknown 45", Keycode.Invalid, Keycode.Invalid, 0x1E8, true),
            new KeyBinding("Unknown 46", Keycode.LeftAlt, Keycode.Invalid, 0x1F0, true),
            new KeyBinding("Unknown 47", Keycode.E, Keycode.Invalid, 0x1F8, true),
            new KeyBinding("Unknown 48", Keycode.LeftAlt, Keycode.Invalid, 0x200, true),
            new KeyBinding("Unknown 49", Keycode.LeftArrow, Keycode.Invalid, 0x208, true),
            new KeyBinding("Unknown 50", Keycode.RightArrow, Keycode.Invalid, 0x210, true),
            new KeyBinding("Unknown 51", Keycode.NumPadEnter, Keycode.Invalid, 0x218, true),
            new KeyBinding("Unknown 52", Keycode.X, Keycode.Invalid, 0x220, true),
            new KeyBinding("Unknown 53", Keycode.Invalid, Keycode.Invalid, 0x228, true),
            new KeyBinding("Unknown 54", Keycode.LeftArrow, Keycode.Invalid, 0x230, true),
            new KeyBinding("Unknown 55", Keycode.RightArrow, Keycode.Invalid, 0x238, true),
            new KeyBinding("Unknown 56", Keycode.Z, Keycode.Invalid, 0x240, true),
            new KeyBinding("Unknown 57", Keycode.Invalid, Keycode.Invalid, 0x248, true),
            new KeyBinding("Unknown 58", Keycode.Space, Keycode.Invalid, 0x250, true),
            new KeyBinding("Unknown 59", Keycode.Invalid, Keycode.Invalid, 0x258, true),
            new KeyBinding("Unknown 60", Keycode.C, Keycode.Invalid, 0x260, true),
            new KeyBinding("Unknown 61", Keycode.R, Keycode.Invalid, 0x268, true),
            new KeyBinding("Unknown 62", Keycode.G, Keycode.Invalid, 0x270, true),
            new KeyBinding("Unknown 63", Keycode.Invalid, Keycode.Invalid, 0x278, true),
            new KeyBinding("Unknown 64", Keycode.UpArrow, Keycode.Invalid, 0x280, true),
            new KeyBinding("Unknown 65", Keycode.DownArrow, Keycode.Invalid, 0x288, true),
            new KeyBinding("Unknown 66", Keycode.RightArrow, Keycode.Invalid, 0x290, true),
            new KeyBinding("Unknown 67", Keycode.LeftArrow, Keycode.Invalid, 0x298, true),
            new KeyBinding("Unknown 68", Keycode.H, Keycode.Invalid, 0x2A0, true),
            new KeyBinding("Forward", Keycode.W, Keycode.Invalid, 0x2A8, false),
            new KeyBinding("Back", Keycode.S, Keycode.Invalid, 0x2B0, false),
            new KeyBinding("Left", Keycode.A, Keycode.Invalid, 0x2B8, false),
            new KeyBinding("Right", Keycode.D, Keycode.Invalid, 0x2C0, false),
            new KeyBinding("Unknown 69", Keycode.Invalid, Keycode.Invalid, 0x2C8, true),
            new KeyBinding("Unknown 70", Keycode.Invalid, Keycode.Invalid, 0x2D0, true),
            new KeyBinding("Unknown 71", Keycode.Invalid, Keycode.Invalid, 0x2D8, true),
            new KeyBinding("Unknown 72", Keycode.Invalid, Keycode.Invalid, 0x2E0, true),
            new KeyBinding("Unknown 72", Keycode.Invalid, Keycode.Invalid, 0x2E8, true),
            new KeyBinding("Unknown 73", Keycode.Invalid, Keycode.Invalid, 0x2F0, true),
            new KeyBinding("Unknown 74", Keycode.Invalid, Keycode.Invalid, 0x2F8, true),
            new KeyBinding("Unknown 75", Keycode.Invalid, Keycode.Invalid, 0x300, true),
            new KeyBinding("Unknown 76", Keycode.Invalid, Keycode.Invalid, 0x308, true),
            new KeyBinding("Unknown 77", Keycode.Invalid, Keycode.Invalid, 0x310, true),
            new KeyBinding("Unknown 78", Keycode.Invalid, Keycode.Invalid, 0x318, true),
            new KeyBinding("Unknown 79", Keycode.Invalid, Keycode.Invalid, 0x320, true),
            new KeyBinding("Unknown 80", Keycode.Invalid, Keycode.Invalid, 0x328, true),
            new KeyBinding("Unknown 81", Keycode.Invalid, Keycode.Invalid, 0x330, true),
            new KeyBinding("Unknown 82", Keycode.Invalid, Keycode.Invalid, 0x338, true),
            new KeyBinding("Unknown 83", Keycode.Invalid, Keycode.Invalid, 0x340, true),
            new KeyBinding("Unknown 84", Keycode.Invalid, Keycode.Invalid, 0x348, true),
            new KeyBinding("Unknown 85", Keycode.Invalid, Keycode.Invalid, 0x350, true),
            new KeyBinding("Unknown 86", Keycode.Invalid, Keycode.Invalid, 0x358, true),
            new KeyBinding("Unknown 87", Keycode.Invalid, Keycode.Invalid, 0x360, true),
            new KeyBinding("Unknown 88", Keycode.Invalid, Keycode.Invalid, 0x368, true),
            new KeyBinding("Unknown 89", Keycode.Invalid, Keycode.Invalid, 0x370, true),
            new KeyBinding("Unknown 90", Keycode.Invalid, Keycode.Invalid, 0x378, true),
            new KeyBinding("Unknown 91", Keycode.Invalid, Keycode.Invalid, 0x380, true),
            new KeyBinding("Unknown 92", Keycode.Invalid, Keycode.Invalid, 0x388, true),
            new KeyBinding("Unknown 93", Keycode.Invalid, Keycode.Invalid, 0x390, true),
            new KeyBinding("Unknown 94", Keycode.Invalid, Keycode.Invalid, 0x398, true),
            new KeyBinding("Unknown 95", Keycode.Invalid, Keycode.Invalid, 0x3A0, true),
            new KeyBinding("Unknown 96", Keycode.Invalid, Keycode.Invalid, 0x3A8, true),
            new KeyBinding("Unknown 97", Keycode.Invalid, Keycode.Invalid, 0x3B0, true),
            new KeyBinding("Unknown 98", Keycode.Invalid, Keycode.Invalid, 0x3B8, true),
            new KeyBinding("Unknown 99", Keycode.Invalid, Keycode.Invalid, 0x3C0, true),
            new KeyBinding("Unknown 100", Keycode.Invalid, Keycode.Invalid, 0x3C8, true),
            new KeyBinding("Unknown 101", Keycode.Invalid, Keycode.Invalid, 0x3D0, true),
            new KeyBinding("Unknown 102", Keycode.Invalid, Keycode.Invalid, 0x3D8, true),
            new KeyBinding("Unknown 103", Keycode.Invalid, Keycode.Invalid, 0x3E0, true),
            new KeyBinding("Unknown 104", Keycode.Invalid, Keycode.Invalid, 0x3E8, true),
            new KeyBinding("Unknown 105", Keycode.Invalid, Keycode.Invalid, 0x3F0, true),
            new KeyBinding("Unknown 106", Keycode.Invalid, Keycode.Invalid, 0x3F8, true),
        };
    }
}
